### ISSUE TITLE
Groups 页面

### ISSUE THREAD

**Issue by JasonQSY** [dbshch/Graduation_project_selection_site#10]
- 组状态“Join，Full，Leave”按钮的优化，Join与Leave应该是either的关系
- 管理员点groups能看到所有的组，并且每个人的名字应该是一个指向他们profile的链接，管理员查看时不应有“Join”或“Leave”，而增加“Delete”
- 如果一个组所有学生都Leave，该组自动被删除

**Comment by JasonQSY** [comment]
@dbshch 加油

**Comment by dbshch** [comment]
现在就没有group管理界面所以没有全部leave这一说啊，只有组长退了就删除的办法

**Comment by dbshch** [comment]
@JasonQSY 给管理员看的用户profile页面搞一下。 @Reapor-Yurnero 组长leave了小组怎么算

**Comment by Reapor-Yurnero** [comment]
小组解散吧，没毛病。所有成员都恢复自由身

**Comment by dbshch** [comment]
committed: [Visit user profile from groups](https://github.com/dbshch/Graduation_project_selection_site/commit/2d2c080bde74bb05b9fc300c02ba53fd75c2cea1)
