### ISSUE TITLE
Profile 页面增加信息

### ISSUE THREAD

**Issue by JasonQSY** [dbshch/Graduation_project_selection_site#11]
- 注册的时候要求登记的信息增加两个：专业、手机号
- My Profile 下增加以上两个信息和身份（学生、管理员）
- My Profile 页面下 顶栏Projects按钮不应处于激活状态，这应该是个bug

**Comment by JasonQSY** [comment]
前端已修复，register现在还没有，单独处理

**Comment by dbshch** [comment]
commit: fuck v2, commit id 239f02d2d4f93b89b347e1086afcff1b142c8626
