### ISSUE TITLE
注册页面

### ISSUE THREAD

**Issue by JasonQSY** [dbshch/Graduation_project_selection_site#12]

**Comment by JasonQSY** [comment]
前端添加了=。= 随便写了个 `Handler` 方便调试

**Comment by Reapor-Yurnero** [comment]
zm

**Comment by dbshch** [comment]
commit: [support jaccount login](https://github.com/dbshch/Graduation_project_selection_site/commit/4cf8e4b49ca292340bd7f2ab0116d554ff04bea7)
