### ISSUE TITLE
Assign Projects 页面

### ISSUE THREAD

**Issue by JasonQSY** [dbshch/Graduation_project_selection_site#13]

**Comment by Reapor-Yurnero** [comment]
fucking crazy

**Comment by JasonQSY** [comment]
finish most of the front-end

**Comment by dbshch** [comment]
@JasonQSY 你这页面我不会用

**Comment by JasonQSY** [comment]
那就交给f少了，我也不懂设计

**Comment by Reapor-Yurnero** [comment]
意思就是每个项目显示了选择者的具体名单，然后下面有一个决定的块，有五个下拉菜单，确定将这项目分配哪五个（或不足五个）人，确认之后，保存刷新一下，这几个被确定的人在其他项目的下拉菜单里就没有了。所有学生都被分配之后，就可以输出一个最终的表格。

**Comment by dbshch** [comment]
assign了之后要不要把别的选了相同project的reject掉。一个project能不能assign多个组，人数有没有上限

**Comment by Reapor-Yurnero** [comment]
assign相当于是最后确认，所以其他选了相同project的就被拒了。assign的时候不一定是按照组来的，组是给ta和老师参考有哪些人想一起干，如果出现特殊情况，也是可以不按照组来assign的，所以设计的时候是每个project可以assign给最多五个人，但是没有对这五个人是不是一个组的限制。

**Comment by dbshch** [comment]
就差钱神的js了

**Comment by dbshch** [comment]
committed: [I think it's done...?](https://github.com/dbshch/Graduation_project_selection_site/commit/7b75e9b151f9ecc7a4a9e993553241a8d20d6b65)
