### ISSUE TITLE
组和报名的bug

### ISSUE THREAD

**Issue by Reapor-Yurnero** [dbshch/Graduation_project_selection_site#18]
BUG1：一同学注册后成为队长后选择了第三第四个project分别作为第一第二选择，但是后台没有显示他的选择，尽管他本人这两个project显示已经是quit the project。在这种情况下，他点击quit the project按钮已经不起作用。
BUG2：B同学想要加入C同学的group，但是在他点击C的Join的时候，他却进入了A（吴承刚）的group。

**Comment by Reapor-Yurnero** [comment]
经过排查，bug2是bug1的导火索，现在凡是没有队员的队伍队长的选择都不会在assign界面里显示，因为B想加入C却加入了A，C成为了没有队员的队伍队长，所以他的选择都不会显示。

**Comment by dbshch** [comment]
committed: [fix issue #18](https://github.com/dbshch/Graduation_project_selection_site/commit/bdd322c277a475a502b4e1875e2e4b58b682734c)
