### ISSUE TITLE
Some Feature Requirement

### ISSUE THREAD

**Issue by Reapor-Yurnero** [dbshch/Graduation_project_selection_site#19]
1.管理员上传图片成功后增加一个success的反馈。
2.学生将一个project作为selection 1 之后，再选别的project时selection1 按钮灰掉不可用，依此类推第二第三选择
3.project界面图片大小控制
4.project界面排序栏和下面的对齐

**Comment by dbshch** [comment]
前端的事情不关我事

**Comment by JasonQSY** [comment]
1. so hard. Our website does not have such a infrastructure.
2. actually back end 
3. 咕咕

**Comment by dbshch** [comment]
fnmdp是后端

**Comment by JasonQSY** [comment]
那我们谈崩了
